"""Fix missing log to items

Revision ID: 173c758ff1d6
Revises: 9f8804c588c5
Create Date: 2024-12-03 09:43:34.499848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '173c758ff1d6'
down_revision = '9f8804c588c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
