"""update enum

Revision ID: 409578d1a099
Revises: 173c758ff1d6
Create Date: 2024-12-09 11:09:48.713828

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '409578d1a099'
down_revision = '173c758ff1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='itemtype',
        new_values=['other', 'flask', 'pump', 'computer'],
        affected_columns=[TableReference(table_schema='public', table_name='item', column_name='type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='itemstatus',
        new_values=['available', 'used', 'maintenance', 'lost', 'discarded'],
        affected_columns=[TableReference(table_schema='public', table_name='item', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='itemstatus',
        new_values=['available', 'in_use', 'maintenance', 'lost', 'discarded'],
        affected_columns=[TableReference(table_schema='public', table_name='item', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='itemtype',
        new_values=['flask', 'pump', 'computer', 'other'],
        affected_columns=[TableReference(table_schema='public', table_name='item', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
